### ISSUE TITLE
Support for RabbitMQ version 3.10.0

### ISSUE THREAD

**Issue by ashleykleynhans** [rabbitmq/rabbitmq-delayed-message-exchange#196] opened 2022-05-05 09:57 UTC
The latest release of the Delayed Message Exchange plugin (version 3.9.0) does not support RabbitMQ version 3.10.0.

```
root@rabbitmq-1:~# rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Enabling plugins on node rabbit@rabbitmq-1:
rabbitmq_delayed_message_exchange
Error:
Failed to enable some plugins:
    rabbitmq_delayed_message_exchange:
        Plugin doesn't support current server version. Actual broker version: "3.10.0", supported by the plugin: ["3.8.0-3.8.x",
                                                                                                                  "3.9.0-3.9.x"]
```

Please release a version that supports RabbitMQ version 3.10.0.

**Comment by michaelklishin** [comment] 2022-05-05 10:20
Duplicate of #194.

**Closed by michaelklishin** 2022-05-05 10:20 UTC

**Comment by michaelklishin** [comment] 2022-05-05 11:09
A new release [is out](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/3.10.0).

**Comment by ashleykleynhans** [comment] 2022-05-05 11:20
Awesome, thanks so much for the quick turn around time, its very much appreciated!
